import type { App } from "./types";

// Generate a starter docker-compose.yml from a selection of apps.
// We derive what we reasonably can from the structured data and CLEARLY mark
// everything uncertain as a placeholder. This is a starting point, not a
// production config — the header comment says so.

function serviceName(app: App): string {
  return app.id.replace(/[^a-z0-9_-]/gi, "-").toLowerCase();
}

function indent(lines: string[], n: number): string {
  const pad = " ".repeat(n);
  return lines.map((l) => (l ? pad + l : l)).join("\n");
}

export type ComposeOptions = {
  // host port offset so multiple apps don't collide on the same default port
  autoIncrementPorts: boolean;
};

export function generateCompose(
  apps: App[],
  opts: ComposeOptions = { autoIncrementPorts: true }
): string {
  if (apps.length === 0) {
    return "# Select one or more apps to generate a starter docker-compose.yml";
  }

  const usedHostPorts = new Set<number>();
  const allocHostPort = (preferred: number | null): number | null => {
    if (preferred == null) return null;
    let p = preferred;
    if (opts.autoIncrementPorts) {
      while (usedHostPorts.has(p)) p += 1;
    }
    usedHostPorts.add(p);
    return p;
  };

  const services: string[] = [];
  const volumes: string[] = [];
  let needsAnyDb = false;

  for (const app of apps) {
    const svc = serviceName(app);
    const s = app.scaffold;
    const lines: string[] = [];

    lines.push(`${svc}:`);
    const body: string[] = [];

    if (s.imageIsGuess) {
      body.push(`# TODO: verify image — this is a best guess, not confirmed`);
    }
    body.push(`image: ${s.image}`);
    body.push(`container_name: ${svc}`);
    body.push(`restart: unless-stopped`);

    // ports
    if (s.port != null) {
      const host = allocHostPort(s.port);
      body.push(`ports:`);
      body.push(`  - "${host}:${s.port}"   # host:container (adjust as needed)`);
    } else {
      body.push(`# ports: configure the published port for this app`);
    }

    // environment
    const env: string[] = [];
    env.push(`- TZ=Etc/UTC`);
    env.push(`- PUID=1000`);
    env.push(`- PGID=1000`);
    if (s.needsDatabase) {
      env.push(`# - DB_HOST=${svc}-db`);
      env.push(`# - DB_NAME=${svc}`);
      env.push(`# - DB_USER=${svc}`);
      env.push(`# - DB_PASSWORD=CHANGE_ME   # use a secret, not plaintext`);
    }
    body.push(`environment:`);
    body.push(...env.map((e) => `  ${e}`));

    // volumes
    if (s.needsVolume) {
      const volName = `${svc}-data`;
      volumes.push(volName);
      body.push(`volumes:`);
      body.push(`  - ${volName}:/config   # TODO: confirm the app's data path`);
    }

    // db dependency placeholder
    if (s.needsDatabase) {
      needsAnyDb = true;
      body.push(`# depends_on:`);
      body.push(`#   - ${svc}-db   # uncomment if you add the db service below`);
    }

    lines.push(indent(body, 2));
    services.push(indent(lines, 2));
  }

  const header = [
    `# ---------------------------------------------------------------------------`,
    `# docker-compose.yml — generated by CanIHost (https://canihost.vercel.app)`,
    `#`,
    `# THIS IS A STARTER SCAFFOLD, NOT A PRODUCTION CONFIG.`,
    `# Images, ports, volumes, and env vars are best-effort guesses derived from`,
    `# the awesome-selfhosted dataset. Lines marked "TODO" / commented out need`,
    `# your attention. Always check each project's official compose example.`,
    `# ---------------------------------------------------------------------------`,
    ``,
    `services:`,
  ].join("\n");

  let out = header + "\n" + services.join("\n\n");

  if (volumes.length) {
    out +=
      "\n\nvolumes:\n" +
      indent(
        [...new Set(volumes)].map((v) => `${v}:`),
        2
      );
  }

  if (needsAnyDb) {
    out +=
      "\n\n# ---------------------------------------------------------------------------\n" +
      "# Some selected apps likely need a database. A typical Postgres service\n" +
      "# looks like the block below — duplicate & rename per app as needed.\n" +
      "# ---------------------------------------------------------------------------\n" +
      "#  example-db:\n" +
      "#    image: postgres:16-alpine\n" +
      "#    restart: unless-stopped\n" +
      "#    environment:\n" +
      "#      - POSTGRES_DB=example\n" +
      "#      - POSTGRES_USER=example\n" +
      "#      - POSTGRES_PASSWORD=CHANGE_ME\n" +
      "#    volumes:\n" +
      "#      - example-db-data:/var/lib/postgresql/data";
  }

  return out + "\n";
}
